# This compose file is intended only for local dev usage.
version: "3.4"
services:
  bsadmin:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    environment:
      DATABASE_URL: postgres://bsadmin_dev:bsadmin_dev@postgres:5432/bsadmin
      DJANGO_SETTINGS_MODULE: bsadmin.settings
    ports:
      - "8009:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
      image: postgres:9.6
      volumes:
        - ./postgres-data/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=bsadmin_dev
        - POSTGRES_USER=bsadmin_dev
        - POSTGRES_DB=bsadmin
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U bsadmin_dev -d bsadmin"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres_data: